version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      target: builder
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
    env_file:
      - .env
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    depends_on:
      - backend