version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      target: builder
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
    env_file:
      - .env
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend