name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Get latest tag
        id: get_version
        run: |
          # Получаем последний тег из ветки main
          LATEST_TAG=$(git describe --tags --abbrev=0 origin/main 2>/dev/null || echo "0.0.0")
          echo "version=$LATEST_TAG" >> $GITHUB_OUTPUT

  deploy:
    needs: version
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.APP_FOLDER }}
            
            if [ ! -d .git ]; then
              git init
              git remote add origin https://github.com/spoterianski/gerber2png-service.git
            fi
            
            git pull origin main

            git fetch origin
            git reset --hard origin/main
            
            # Обновляем версию в footer
            sed -i "s/Version: .*/Version: ${{ needs.version.outputs.version }}/" frontend/src/App.tsx
            
            sudo docker-compose down || true
            
            sudo docker-compose build --no-cache
            sudo docker-compose up -d
            
            sudo docker image prune -f 