name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ${{ secrets.APP_FOLDER }}
            cd ${{ secrets.APP_FOLDER }}

            if [ ! -d .git ]; then
              git init
              git remote add origin https://github.com/spoterianski/gerber2png-service.git
            fi

            git fetch origin
            git reset --hard origin/main
            
            sudo docker-compose down || true
            
            sudo docker-compose build --no-cache
            sudo docker-compose up -d
            
            sudo docker image prune -f 